"""
STATVAULT AI - Phase 7: Similar Player Search
File: src/models/player_similarity.py
"""

import os
import pickle
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

# ==========================================
# 1. CONFIGURATION & PATHS
# ==========================================
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
DATA_PATH = os.path.join(BASE_DIR, 'data', 'features', 'player_features.csv')
MODEL_DIR = os.path.join(BASE_DIR, 'models')
SIMILARITY_INDEX_PATH = os.path.join(MODEL_DIR, 'similarity_index.pkl')
PLAYER_NAMES_PATH = os.path.join(MODEL_DIR, 'player_names.pkl')

# Must match the exact column names generated by Phase 4
FEATURE_COLUMNS = [
    'age', 'height', 'weight', 'overall_rating', 'potential',
    'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physical'
]

# ==========================================
# 2. DATA LOADING & PREPROCESSING
# ==========================================
def load_and_preprocess_data():
    print("Loading player features...")
    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(f"Data not found at {DATA_PATH}. Please run Phase 4 first.")
    
    df = pd.read_csv(DATA_PATH)
    
    # Find the player name column dynamically
    name_col = None
    for col in ['short_name', 'player_name', 'name', 'long_name']:
        if col in df.columns:
            name_col = col
            break
            
    if not name_col:
        print("️ WARNING: No name column found. Using placeholder names.")
        df['placeholder_name'] = [f"Player_{i}" for i in range(len(df))]
        name_col = 'placeholder_name'
    else:
        print(f"✅ Identified '{name_col}' as the player name column.")

    # Filter to available features
    available_features = [col for col in FEATURE_COLUMNS if col in df.columns]
    if not available_features:
        raise ValueError(f"No matching feature columns found. Available: {df.columns.tolist()}")
        
    # Clean data
    df_clean = df.dropna(subset=available_features)
    for col in available_features:
        df_clean[col] = df_clean[col].fillna(df_clean[col].median())
        
    # Extract names and features
    player_names = df_clean[name_col].astype(str).str.strip().values
    X = df_clean[available_features].values
    
    # Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    return player_names, X_scaled, scaler

# ==========================================
# 3. BUILD AND SAVE INDEX
# ==========================================
def build_and_save_similarity_index():
    player_names, X_scaled, scaler = load_and_preprocess_data()
    
    print("Computing Cosine Similarity Matrix...")
    os.makedirs(MODEL_DIR, exist_ok=True)
    
    similarity_data = {'X_scaled': X_scaled, 'scaler': scaler}
    with open(SIMILARITY_INDEX_PATH, 'wb') as f:
        pickle.dump(similarity_data, f)
        
    with open(PLAYER_NAMES_PATH, 'wb') as f:
        pickle.dump(player_names, f)
        
    print(f"✅ Successfully saved similarity index to {SIMILARITY_INDEX_PATH}")

# ==========================================
# 4. SEARCH FUNCTION
# ==========================================
def find_similar_players(player_name, top_n=5):
    if not os.path.exists(SIMILARITY_INDEX_PATH):
        raise FileNotFoundError("Index not found. Run build_and_save_similarity_index() first.")
        
    with open(SIMILARITY_INDEX_PATH, 'rb') as f:
        data = pickle.load(f)
    with open(PLAYER_NAMES_PATH, 'rb') as f:
        player_names = pickle.load(f)
        
    X_scaled = data['X_scaled']
    player_names_lower = [name.lower() for name in player_names]
    target_name_lower = player_name.lower().strip()
    
    if target_name_lower not in player_names_lower:
        partial = [name for name in player_names if target_name_lower in name.lower()]
        if partial:
            return f"Player '{player_name}' not found exactly. Did you mean: {partial[:5]}?"
        return f"Player '{player_name}' not found. First 5 in DB: {player_names[:5].tolist()}"
            
    player_idx = player_names_lower.index(target_name_lower)
    player_vector = X_scaled[player_idx].reshape(1, -1)
    similarities = cosine_similarity(player_vector, X_scaled).flatten()
    similar_indices = similarities.argsort()[::-1][1:top_n+1]
    
    return [(player_names[idx], round(similarities[idx], 4)) for idx in similar_indices]

# ==========================================
# 5. MAIN EXECUTION (THIS WAS MISSING!)
# ==========================================
if __name__ == "__main__":
    print("--- Building Similarity Index ---")
    build_and_save_similarity_index()
    
    print("\n--- Testing Similar Player Search ---")
    target_player = "Kevin De Bruyne"
    print(f"Searching for players similar to: {target_player}\n")
    
    results = find_similar_players(target_player, top_n=5)
    
    if isinstance(results, str):
        print(results)
    else:
        print(f"Top 5 players similar to {target_player}:")
        for rank, (name, score) in enumerate(results, 1):
            print(f"{rank}. {name} (Score: {score})")